from karl.v2 import *

left_eye.red.on()
sleep(2)
left_eye.red.off()
left_eye.green.on()
sleep(2)
left_eye.green.off()
left_eye.blue.on()
sleep(2)
left_eye.blue.off()

right_eye.red.on()
sleep(2)
right_eye.red.off()
right_eye.green.on()
sleep(2)
right_eye.green.off()
right_eye.blue.on()
sleep(2)
right_eye.blue.off()